### PR TITLE
test: Deploy agents on various Kubernetes versions

### PR DESCRIPTION
**Pull request by tomkerkhove**
Deploy agents on various Kubernetes versions to verify compatability

### CODE REVIEW

**Comment by tomkerkhove** [comment]
@akostic-kostile #70 you have contributed a way to make it more secure to deploy our scraper.

Unfortunately there is a field that is not available in Kubernetes v1.17/v1.18, any ways to skip this?

In https://github.com/promitor/charts/pull/70/files#diff-aa8a8f628991c5d8f06fdc25d3fcc91d0cb935572b3870e3958a5dfcd1fd3ad8R192

**Comment by akostic-kostile** [comment]
Hey @tomkerkhove,

I took a look at the issue and you're correct, seccompProfile was added as pod level security context property in version 1.19.x, before it was available as an annotation `seccomp.security.alpha.kubernetes.io`. One thing to keep in mind here is the fact that Kubernetes project moves at very high speed, the only supported versions of k8s at this time are 1.20+, everything before is EOL already (https://endoflife.date/kubernetes). In my opinion it makes sense to officially only test the chart on currently supported versions.

As for the unofficial support, well, the way we implemented these changes makes it extremely easy for someone to override what is in the values.yaml, so I don't see much of a problem there. We can think about updating README.md to make it clear that using version <1.19.x would require some manual intervention on the user's part.

The real question here is should we try and automate so >1.19 get seccompProfile in securityContext while <1.19 get annotated correctly? Its possible Helm allows us to do check for api version and do something with that info (I'm not sure, never tried something like that), but is it really worth the hassle to do that for 1.18 considering it's maintenance support ended 6 months ago?

**Comment by tomkerkhove** [comment]
> Its possible Helm allows us to do check for api version and do something with that info (I'm not sure, never tried something like that)

It does, so I'll add that. Do you have some docs on the previously supported approach?

> but is it really worth the hassle to do that for 1.18 considering it's maintenance support ended 6 months ago?

That's a valid concern but it's not up to me to enforce Kubernetes versions, unless there is no other way.

**Comment by tomkerkhove** [comment]
Merging with known issue tracked in #80

**Pull request merged**
