### PR TITLE
fix:  Allow empty metric declarations

### LINKED ISSUE #64: Default promitor scraper values generates invalid metrics-declaration.yaml configuration
When leaving the metrics value at it's default `metrics: []` it generates an invalid `metrics-declarions.yaml` configuration due to creating a line break bettween `metrics:` and `[]`

## Expected Behavior

Default metrics value should deploy a promitor instance with a valid configuration.

valid config:
```yaml
metrics: []
```

## Actual Behavior

Promitor fails to launch due to invalid `metrics-declarions.yaml` configuration.

invalid config:
```yaml
metrics:
  []
```

## Steps to Reproduce the Problem

  1. Deploy promitor scraper with default values for metrics

## Specifications

  - Version: 2.6.0
  - Platform:
  - Subsystem:

### PR DESCRIPTION
**Pull request by danielpof**
…lements

Fixes #64

### CODE REVIEW

**Comment by tomkerkhove** [comment]
Thanks! Did you try running the chart locally?

**Comment by daniel-anova** [comment]
only ` helm template --debug .` against default values and the example.

Outputs:
```
  metrics-declaration.yaml: |-
    version: v1
    azureMetadata:
      tenantId:
      subscriptionId:
      resourceGroupName: promitor
      cloud: Global
    metricDefaults:
      aggregation:
        interval: 00:05:00
      scraping:
        schedule: "*/5 * * * *"
    metrics: []
```

```
  metrics-declaration.yaml: |-
    version: v1
    azureMetadata:
      tenantId: c8819874-9e56-4e3f-b1a8-1c0325138f27
      subscriptionId: 0f9d7fea-99e8-4768-8672-06a28514f77e
      resourceGroupName: promitor
      cloud: Global
    metricDefaults:
      aggregation:
        interval: 00:05:00
      scraping:
        schedule: "0 * * ? * *"
    metrics:
    - azureMetricConfiguration:
        aggregation:
          type: Average
        metricName: MemoryPercentage
      description: Average percentage of memory usage on an Azure App Plan
      name: promitor_demo_appplan_percentage_cpu
      resourceType: AppPlan
      resources:
      - appPlanName: promitor-app-plan
        resourceGroupName: promitor-sources
   <...>
```

**Comment by tomkerkhove** [comment]
I will ship the fix later today if this is blocking you?

**Comment by daniel-anova** [comment]
> I will ship the fix later today if this is blocking you?

The issue only presented itself when getting it up and running for the first time with a minimal config.

I've since deployed promitor with a fleshed out configuration including metrics, so not being blocked by this.

**Comment by tomkerkhove** [comment]
Ok then I will add it to the new major release, thanks!

Let me know if you run in any other issues or want to become a listed end-user!

**Pull request merged**
