### PR TITLE
feat: Enable Batch Scraping Configuration

### PR DESCRIPTION
**Pull request by hkfgo**
Fixes #

### CODE REVIEW

**Review by tomkerkhove — APPROVED** [review]

**Comment by hkfgo** [comment]
Not sure why those deploy checks failed, since Helm lint appears to think this chart is perfectly fine :) 

I'm gonna pull in this chart to run in our staging env. Will report back

**Comment by hkfgo** [comment]
Btw, it'd be great if you can cut a new Promitor release soon(no pressure)! We'd accumulated a good amount of feature changes as well as CVEs(https://github.com/tomkerkhove/promitor/pull/2538 and https://github.com/tomkerkhove/promitor/pull/2542). Users like me are eager to try out a new release in production.

**Review by tomkerkhove — APPROVED** [review]

**Comment by tomkerkhove** [comment]
Sure but docs/helm needs to be ready as well.

Did you try this Helm chart locally? I see startup failures here, but can be outdated secret

**Comment by hkfgo** [comment]
> Sure but docs/helm needs to be ready as well.
> 
> Did you try this Helm chart locally? I see startup failures here, but can be outdated secret

I suspect it's an outdated secret. I tried running with `configmap` and `values` files from master, and still couldn't pass the CI. Do you mind checking those? 

The logs aren't too helpful here :/ It looks like the top of the table was cut off, so we can't see what step has failed

```
Current container logs
┃ Resource Discovery               │ Success │ Everything is well-configured.  ┃
┃ Atlassian Statuspage Metric Sink │ Success │ Everything is well-configured.  ┃
┃ OpenTelemetry Collector Metric   │ Success │ Everything is well-configured.  ┃
┃ Sink                             │         │                                 ┃
┃ Prometheus Scraping Endpoint     │ Success │ Everything is well-configured.  ┃
┃ Metric Sink                      │         │                                 ┃
┃ StatsD Metric Sink               │ Success │ Everything is well-configured.  ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┷━━━━━━━━━┷━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

**Comment by hkfgo** [comment]
And yeah, I've tested my chart changes in staging env, where I configured our Promitor deployments to do batch scraping by default. Everything looks to be working so far

**Comment by tomkerkhove** [comment]
I trust you

**Pull request merged**
