### PR TITLE
chore: release emptyDir PSP fix

### PR DESCRIPTION
**Pull request by etiennetremel**
Last fix introduced by https://github.com/promitor/charts/pull/76 hasn't been released. This PR bump the version of the promitor-agent-scraper chart to release the patch.

### CODE REVIEW

**Comment by tomkerkhove** [comment]
This was pending a new agent version but happy to release a newer version earlier.

Can you please follow https://github.com/promitor/charts/blob/main/CONTRIBUTING.md#shipping-a-new-version?

**Comment by etiennetremel** [comment]
Thanks @tomkerkhove , I updated the index

**Comment by tomkerkhove** [comment]
There's an issue with a given field (see #79) so will have to fix this first.

**Comment by tomkerkhove** [comment]
We should be good to go, would you mind merging main and repackaging the new version based please?

**Comment by etiennetremel** [comment]
@tomkerkhove rebased and ready to go!

**Pull request merged**
